logging:
  level:
    org.springframework : info


management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8100


spring:
  application:
    name: todo-service
  security:
    user:
      name: jonan
      password: 8793887343

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/








